package com.corprag.security;

import java.util.Locale;
import java.util.Set;
import org.springframework.stereotype.Component;

@Component
public class CompromisedPasswordChecker {

    private static final Set<String> COMMON_PASSWORDS = Set.of(
            "123456",
            "password",
            "12345678",
            "qwerty",
            "123456789",
            "12345",
            "1234",
            "111111",
            "1234567",
            "dragon",
            "123123",
            "baseball",
            "abc123",
            "football",
            "monkey",
            "letmein",
            "shadow",
            "master",
            "666666",
            "qwertyuiop",
            "123321",
            "mustang",
            "1234567890",
            "michael",
            "654321",
            "superman",
            "1qaz2wsx",
            "7777777",
            "121212",
            "000000",
            "qazwsx",
            "123qwe",
            "killer",
            "trustno1",
            "jordan",
            "jennifer",
            "zxcvbnm",
            "asdfgh",
            "hunter",
            "buster",
            "soccer",
            "harley",
            "batman",
            "andrew",
            "tigger",
            "sunshine",
            "iloveyou",
            "2000",
            "charlie",
            "robert",
            "thomas",
            "hockey",
            "ranger",
            "daniel",
            "starwars",
            "klaster",
            "112233",
            "george",
            "asshole",
            "computer",
            "michelle",
            "jessica",
            "pepper",
            "1111",
            "zxcvbn",
            "555555",
            "11111111",
            "131313",
            "freedom",
            "777777",
            "pass",
            "fuck",
            "maggie",
            "159753",
            "aaaaaa",
            "ginger",
            "princess",
            "joshua",
            "cheese",
            "amanda",
            "summer",
            "love",
            "ashley",
            "nicole",
            "chelsea",
            "biteme",
            "matthew",
            "access",
            "yankees",
            "987654321",
            "dallas",
            "austin",
            "thunder",
            "taylor",
            "matrix",
            "mobilemail",
            "mom",
            "monitor",
            "monitoring",
            "montana",
            "moon",
            "moscow",
            "welcome",
            "welcome1",
            "welcome12",
            "welcome123",
            "admin",
            "admin1",
            "admin12",
            "admin123",
            "qwerty1",
            "qwerty12",
            "qwerty123",
            "root",
            "toor",
            "changeme",
            "changeme1",
            "changeme123",
            "letmein1",
            "letmein12",
            "letmein123",
            "password1",
            "pssw0rd",
            "corporate",
            "company",
            "corp",
            "user",
            "user1",
            "user123",
            "login",
            "login123",
            "password12",
            "password123",
            "qwerty12345",
            "adminadmin",
            "admin123456",
            "corporate123",
            "company12345");

    public boolean isCompromised(String password) {
        if (password == null) {
            return false;
        }
        String normalized = password.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]", "");
        return COMMON_PASSWORDS.contains(normalized);
    }
}
