"""Generate frontend permission-code constants from api-v1.yaml."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts" / "openapi" / "api-v1.yaml"
OUTPUT = ROOT / "frontend" / "js" / "generated" / "permission-codes.js"


def load_permission_codes(contract_path: Path) -> list[str]:
    lines = contract_path.read_text(encoding="utf-8").splitlines()
    in_schema = False
    in_enum = False
    codes: list[str] = []
    for line in lines:
        if line.startswith("    PermissionCode:"):
            in_schema = True
            continue
        if in_schema and line.startswith("    ") and not line.startswith("      ") and line.strip().endswith(":"):
            break
        if not in_schema:
            continue
        if line.strip() == "enum:":
            in_enum = True
            continue
        if in_enum:
            stripped = line.strip()
            if stripped.startswith("- "):
                codes.append(stripped[2:].strip().strip('"').strip("'"))
                continue
            if stripped and not stripped.startswith("#"):
                break
    if not codes:
        raise ValueError("PermissionCode enum is missing or invalid")
    return codes


def render(codes: list[str]) -> str:
    labels = {code: code.replace("_", " ").replace(".", " / ") for code in codes}
    return "\n".join(
        [
            "// Generated by scripts/generate_frontend_permission_codes.py. Do not edit by hand.",
            "",
            f"export const PERMISSION_CODES = Object.freeze({json.dumps(codes, indent=2)});",
            "",
            f"export const PERMISSION_LABELS = Object.freeze({json.dumps(labels, indent=2)});",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", type=Path, default=CONTRACT)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    content = render(load_permission_codes(args.contract))
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != content:
            raise SystemExit(f"{args.output.relative_to(ROOT)} is out of date")
        print(f"{args.output.relative_to(ROOT)} is up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(args.output.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
